name: pr-check
  
on:
  workflow_dispatch:
  pull_request:
    types: [ 'opened', 'synchronize' ]
  push:  
    branches:  
      - main

permissions:
  contents: write
  pull-requests: read
  statuses: write
  security-events: write

  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Install Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:  
        go-version: '1.20.3'
    - name: Setup latest Terraform  
      uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
      with:
        terraform_wrapper: false
    - name: Remove generated directory  
      run: rm -rf generated
    - name: Run go mod tidy
      run: go mod tidy
    - name: generate schemas
      run: |
        go run cmd/main.go -refresh true
        go mod tidy
    - name: Run tests for generated package
      run: go test github.com/${{ github.repository }}/v4/generated/...
    - name: Run Gosec Security Scanner
      uses: securego/gosec@aebe20cfba724c45b6d6a2d8946ffa41a00f628c # master
      with:
        args: '-exclude=G101 ./...'
    - name: Run GolangCI-Lint
      uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
      with:
        version: latest
        skip-cache: true
    - name: Initialize CodeQL
      uses: github/codeql-action/init@04daf014b50eaf774287bf3f0f1869d4b4c4b913 # v2.21.7
      with:
        languages: "go"
    - name: Autobuild
      uses: github/codeql-action/autobuild@04daf014b50eaf774287bf3f0f1869d4b4c4b913 # v2.21.7
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@04daf014b50eaf774287bf3f0f1869d4b4c4b913 # v2.21.7
